import axios from 'axios';
import type { EmailSummary, ProcessedEmail } from '../../types/email';
import type { EmailSender as IEmailSender, EmailComposer as IEmailComposer } from '../../types/modules';
import { GMAIL_API_BASE } from '../../constants';

export class EmailComposer implements IEmailComposer {
  composeHtml(summary: EmailSummary): string {
    const formatDate = (date: Date): string => {
      return new Date(date).toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    };

    const renderEmailList = (emails: ProcessedEmail[], title: string, icon: string): string => {
      if (emails.length === 0) return '';

      const items = emails
        .map((email) => {
          let details = '';
          if (email.extractedData.amounts.length > 0) {
            details += `<br><small>💵 Amount: ${email.extractedData.amounts.join(', ')}</small>`;
          }
          if (email.extractedData.dueDates.length > 0) {
            details += `<br><small>📆 Due: ${email.extractedData.dueDates.map((d) => formatDate(d)).join(', ')}</small>`;
          }
          if (email.extractedData.times.length > 0) {
            details += `<br><small>⏰ Time: ${email.extractedData.times.join(', ')}</small>`;
          }
          if (email.extractedData.urls.length > 0) {
            details += `<br><small>🔗 <a href="${email.extractedData.urls[0]}">${email.extractedData.urls[0]}</a></small>`;
          }
          if (email.extractedData.otpCodes.length > 0) {
            details += `<br><small>🔐 Code: <strong>${email.extractedData.otpCodes[0]}</strong></small>`;
          }

          return `<li style="margin-bottom: 12px;">
            <strong>${email.subject}</strong><br>
            <small style="color: #666;">From: ${email.from}</small>
            ${details}
          </li>`;
        })
        .join('');

      return `
        <div style="margin-bottom: 24px;">
          <h2 style="color: #4F46E5; border-bottom: 2px solid #E5E7EB; padding-bottom: 8px;">
            ${icon} ${title} (${emails.length})
          </h2>
          <ul style="list-style: none; padding: 0;">${items}</ul>
        </div>
      `;
    };


    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
          h1 { color: #1F2937; }
          a { color: #4F46E5; }
        </style>
      </head>
      <body>
        <h1>📧 Your Daily Email Summary</h1>
        <p style="color: #666;">Generated on ${formatDate(summary.generatedAt)}</p>
        
        ${renderEmailList(summary.important, 'Important', '⭐')}
        ${renderEmailList(summary.bills, 'Bills', '💰')}
        ${renderEmailList(summary.jobs, 'Jobs', '💼')}
        ${renderEmailList(summary.meetings, 'Meetings', '📅')}
        ${renderEmailList(summary.attachments, 'Attachments', '📎')}
        ${renderEmailList(summary.otp, 'OTP Codes', '🔐')}
        
        <hr style="border: none; border-top: 1px solid #E5E7EB; margin: 24px 0;">
        <p style="color: #9CA3AF; font-size: 12px;">
          This summary was generated by AutoMail Day Planner. All processing was done locally in your browser.
        </p>
      </body>
      </html>
    `;
  }

  composeReminder(email: { subject: string; from: string; details: string }): string {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
          .reminder-box { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 1.5rem; border-radius: 0.5rem; margin: 1rem 0; }
          .email-content { background: #f9fafb; padding: 1rem; border-radius: 0.5rem; margin-top: 1rem; white-space: pre-wrap; }
        </style>
      </head>
      <body>
        <h1>⏰ Reminder from AutoMail</h1>
        <div class="reminder-box">
          <h2 style="color: #f59e0b; margin-top: 0;">📧 ${email.subject}</h2>
          <p><strong>From:</strong> ${email.from}</p>
          <div class="email-content">${email.details}</div>
        </div>
        <p style="color: #9CA3AF; font-size: 12px; margin-top: 2rem;">
          This reminder was scheduled via AutoMail Day Planner.
        </p>
      </body>
      </html>
    `;
  }

  composeRfc822(to: string, subject: string, html: string): string {
    const message = [
      `To: ${to}`,
      `Subject: ${subject}`,
      'MIME-Version: 1.0',
      `Content-Type: text/html; charset=utf-8`,
      '',
      html,
    ].join('\r\n');

    // Base64 encode for Gmail API (URL-safe)
    return btoa(unescape(encodeURIComponent(message)))
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');
  }
}

export class EmailSender implements IEmailSender {
  private accessToken: string;
  private composer: EmailComposer;

  constructor(accessToken: string) {
    this.accessToken = accessToken;
    this.composer = new EmailComposer();
  }

  async scheduleReminder(to: string, emailSubject: string, emailFrom: string, emailDetails: string, scheduledTime: Date): Promise<void> {
    const subject = `⏰ Reminder: ${emailSubject}`;
    const html = this.composer.composeReminder({ subject: emailSubject, from: emailFrom, details: emailDetails });
    const raw = this.composer.composeRfc822(to, subject, html);

    try {
      await axios.post(
        `${GMAIL_API_BASE}/users/me/drafts`,
        {
          message: {
            raw,
            labelIds: ['DRAFT'],
            threadId: null,
          }
        },
        {
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
            'Content-Type': 'application/json',
          },
        }
      );
    } catch (error) {
      throw new Error('Failed to schedule reminder.');
    }
  }

  async sendSummary(summary: EmailSummary, userEmail: string, recipientEmail?: string): Promise<void> {
    const today = new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const subject = `Your Daily Email Summary - ${today}`;
    const html = this.composer.composeHtml(summary);
    const raw = this.composer.composeRfc822(recipientEmail || userEmail, subject, html);

    try {
      await axios.post(
        `${GMAIL_API_BASE}/users/me/messages/send`,
        { raw },
        {
          headers: {
            Authorization: `Bearer ${this.accessToken}`,
            'Content-Type': 'application/json',
          },
        }
      );
    } catch (error) {
      throw new Error('Failed to send email summary. Please try again.');
    }
  }
}

export function createEmailSender(accessToken: string): EmailSender {
  return new EmailSender(accessToken);
}

export function createEmailComposer(): EmailComposer {
  return new EmailComposer();
}
